<?php
/**
 * @file
 * Code for the OS block functionality.
 */
drupal_add_js(drupal_get_path('module', 'os_events') . '/os_events.js');

/**
 * Implements hook_form_alter().
 */
function os_events_form_alter(&$form, &$form_state, $form_id){
  global $user;
  if($form_id == 'event_node_form') {
    drupal_set_title('Submit an event below');
    $form['field_event_submitter_name'][LANGUAGE_NONE][0]['value']['#default_value']  = $user->name;
    $form['field_event_submitter_email'][LANGUAGE_NONE][0]['email']['#default_value']  = $user->mail;
  }
}

/**
 *  Implements hook_menu().
 */
function os_events_menu() {
  $items = array();
  $items['admin/content/opensource-events'] = array(
    'title' => 'Events',
    'page callback' => 'drupal_goto',
    'page arguments' => array('moderation-queue/events/all'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  /**
	 * Monthly view
	 */
	$items['admin/content/opensource-events/monthly'] = array(
		'title' => 'Monthly View',
		'page callback' => 'drupal_goto',
		'page arguments' => array('resources/conferences-and-events-monthly'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_TASK,
	);
	$items['admin/content/opensource-events/monthly/page-title'] = array(
		'title' => 'Page title',
		'page callback' => 'drupal_goto',
		'page arguments' => array('admin/structure/pages/nojs/operation/page-conferences_and_events/handlers/page_conferences_and_events_panel_context/content'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_TASK,
	);
	$items['admin/content/opensource-events/monthly/intro'] = array(
    'title' => 'Intro',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/views/nojs/config-item/event_calendar_list/panel_pane_1/header/area'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/opensource-events/monthly/default-text'] = array(
    'title' => 'Default text',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/views/nojs/config-item/event_calendar_list/panel_pane_1/empty/area'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

	/**
   * Alphabetical view
   */

  $items['admin/content/opensource-events/alphabetical'] = array(
    'title' => 'Alphabetical View',
    'page callback' => 'drupal_goto',
    'page arguments' => array('resources/conferences-and-events-list'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/opensource-events/alphabetical/intro'] = array(
    'title' => 'Intro',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/views/nojs/config-item/event_listing_alphabetical/panel_pane_1/header/area'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/opensource-events/alphabetical/page-title'] = array(
    'title' => 'Page title',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/pages/nojs/operation/page-event_list_panel/handlers/page_event_list_panel_panel_context/content'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/opensource-events/alphabetical/default-text'] = array(
    'title' => 'Default text',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/views/nojs/config-item/event_listing_alphabetical/panel_pane_1/empty/area'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  /**
   * Other
   */
  $items['admin/content/opensource-events/moderation-queue'] = array(
    'title' => 'Moderation queue',
    'page callback' => 'drupal_goto',
    'page arguments' => array('moderation-queue/events/all'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
  );
  return $items;
}
