<?php

/**
 * @file
 * Custom points code for opensource.com
 */

/**
 * Implementation of hook_userpoints
 *
 * This checks various values before awarding points such as the daily limit.
 */

function opensource_points_userpoints($op, &$params) {
  global $user;
  
  switch($op){
    case 'points before':
      $query = "SELECT SUM(points) FROM {userpoints} WHERE last_update >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AND uid = %d";
      $points_today = db_result(db_query($query, $params['uid']));
      
      // If the user has earned more than points today and it is the currently logged in user.
      if($points_today >= 10 && $user->uid == $params['uid']){
        drupal_set_message("Sorry, you have reached the maximum number of 10 points you can be awarded in one day.", "status");
        return false;
      }
      
  }
}

/**
 * Implementation of hook_mail_alter
 *
 * This checks that a user has opted in to receive the points notification mail.
 */
function opensource_points_mail_alter(&$message){
  switch($message){
    case 'userpoints_role_userpoints_role':
      // If the user has not opted in to this mail send, don't send it.
      $user = user_load(array('mail' => $message['to']));
      if(!$user->profile_points_notifications){
        unset($message);
      }   
  }
}