<?php

function opensource_events_init(){
  drupal_add_css(drupal_get_path('module', 'opensource_events') .'/opensource_events.css');
  drupal_add_js(drupal_get_path('module', 'opensource_events') . '/opensource_events.js');
}

include_once('opensource_events.features.inc');

function opensource_events_views_api() {
  return array('api' => 2.0);
}


/**
 * Implements hook_theme().
 */

function opensource_events_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_fields__events_listing_alphabetical' => array(
      'original hook' => 'views_view_fields',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_fields',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view-fields--events-listing-alphabetical',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'views_view__events_listing_alphabetical__page' => array(
      'original hook' => 'views_view',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view',
      ),
      'arguments' => array('view' => NULL),
      'template' => 'views-view--events-listing-alphabetical--page',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'views_view_fields__events_listing_monthly_new' => array(
      'original hook' => 'views_view_fields',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_fields',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view-fields--events-listing-monthly-new',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'views_view__events_listing_monthly_new' => array(
      'original hook' => 'views_view',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view',
      ),
      'arguments' => array('view' => NULL),
      'template' => 'views-view--events-listing-monthly-new',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'calendar_month__events_listing_monthly_new' => array(
      'original hook' => 'calendar_month',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_calendar_month',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'rows' => NULL, 'title' => NULL),
      'template' => 'calendar-month--events-listing-monthly-new',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'date_navigation__events_listing_monthly_new__date_nav_1' => array(
      'original hook' => 'date_navigation',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_date_navigation',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'rows' => NULL, 'title' => NULL),
      'template' => 'date-navigation--events-listing-monthly-new--date-nav-1',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'date_navigation__events_listing_monthly_new__date_nav_2' => array(
      'original hook' => 'date_navigation',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_date_navigation',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'rows' => NULL, 'title' => NULL),
      'template' => 'date-navigation--events-listing-monthly-new--date-nav-2',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'views_view__events_listing_monthly_new__attachment_1' => array(
      'original hook' => 'views_view',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view',
      ),
      'arguments' => array('view' => NULL),
      'template' => 'views-view--events-listing-monthly-new--attachment-1',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
    'views_view__events_listing_alphabetical__page_1' => array(
      'original hook' => 'views_view',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view',
      ),
      'arguments' => array('view' => NULL),
      'template' => 'views-view--events-listing-alphabetical--page-1',
      'path' => drupal_get_path('module', 'opensource_events') . '/templates',
    ),
  );
}

function opensource_events_menu() {

  $items = array();

  $items['event-submitted-for-review'] = array(
    'title' => t('Thank you.'),
    'page callback' => '_opensource_events_success',
    'access callback' => TRUE,
  );

  return $items;
}

function _opensource_events_success() {
  return t('Your event has been submitted for review. Check out our ') . l(t('event listings'), 'resources/conferences-and-events-monthly') . t(' or ') . l(t('submit another event'), 'node/add/event') . '.';
}
function opensource_events_form_alter(&$form, &$form_state, $form_id) {
  if($form_id=='event_node_form') {
    drupal_set_title('Submit an event below');
    $form['#attributes'] = array('class' => 'event-form');
    $form['buttons']['submit']['#submit'][] = '_opensource_events_redirect_handler';
  }
}

function _opensource_events_redirect_handler($form, &$form_state) {
  if($form_state['nid']) {
    $form_state['redirect'] = 'event-submitted-for-review';
  }
}

function opensource_events_theme_registry_alter(&$theme_registry) {
  $modulepath = drupal_get_path('module', 'opensource_events');
  array_unshift($theme_registry['node']['theme paths'], $modulepath . '/templates');
}

function opensource_events_preprocess_node(&$vars) {
  $vars['template_files'][] = 'node-event-type';
}
/*function opensource_events_theme_registry_alter(&$theme_registry) {
  $theme_path = drupal_get_path('module', 'opensource_events');
  // $theme_registry['calendar_month_node']['path'] = $theme_path . '/templates';
  $theme_registry['calendar_month_node']['theme path'] = $theme_path;
  $theme_registry['calendar_month_node']['theme paths'][0] = $theme_path . '/templates';
}*/
