<?php

define('LOGINLOGOUT_DEFAULT_URLS', "user/login\nuser/logout\nuser");

/**
 * Implementation of hook_user().
 */
function loginlogout_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'logout':
      if (!empty($_GET['destination'])) {
        global $user;
        $user_temp = $user;
        $user = drupal_anonymous_user();
        $item = menu_get_item($_GET['destination']);
        if (empty($item['access'])) {
          unset($_GET['destination']);
          unset($_GET['destination']);
        }
        $user = $user_temp;
      }
      break;
  }
}

/**
 * Implementation of hook_init().
 */
function loginlogout_init() {

  // Prevent running if on login form.
  if (!user_is_logged_in() && ($_GET['q'] == 'user' || $_GET['q'] == 'user/login')) {
    return;
  }

  // Add js file.
  drupal_add_js(drupal_get_path('module', 'loginlogout') . '/loginlogout.js');

  $destination = drupal_get_destination();

  $settings = array(
    'loginlogout' => array(
      'urls' => array(),
    ),
  );

  $options = array(
    'query' => $destination,
  );

  $purl_options = array(
    'purl' => array(
      'disabled' => TRUE,
    ),
  );

  $purl_options_with_dest = array(
    'query' => $destination,
    'purl' => array(
      'disabled' => TRUE,
    ),
  );

  $paths = explode("\n", variable_get('loginlogout_urls', LOGINLOGOUT_DEFAULT_URLS));

  foreach ($paths as $path) {
    if (($path = trim($path)) && ($url = url($path))) {
      // User is not a relavent url for
      if ($path == 'user' && user_is_logged_in()) {
        continue;
      }
      $settings['loginlogout']['urls'][$url] = url($path, $options);
      if (module_exists('purl') && ($url = url($path, $purl_options))) {
        $settings['loginlogout']['urls'][$url] = url($path, $purl_options_with_dest);
      }
    }
  }

  drupal_add_js($settings, array('type' => 'setting', 'scope' => JS_DEFAULT));
}

/**
 * Implementation of hook_menu().
 */
function loginlogout_menu() {
  $items['admin/config/loginlogout'] = array(
    'title' => 'Login logout settings',
    'description' => 'Configure login logout settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('loginlogout_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'loginlogout.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
