<?php

/**
 * @file
 * Add custom variables to opensource.com for Omniture SiteCatalyst.
 */

/**
 * Implementation of hook_omniture_variables().
 */
function opensource_omniture_omniture_variables($main) {
  $page_name = 'opensource';  // The sitename.
  // Add the channel name.
  if (module_exists('og') && $group_node = og_get_group_context()) {
    $page_name .= '|'. opensource_omniture_clean($group_node->title);
  }
  elseif (arg(0) == 'search') {
    $arguments = arg();
    foreach ($arguments as $argument) {
       $page_name .= '|'. opensource_omniture_clean($argument);
    }
  }

  // Add the content type and title.
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    $page_name .= '|'. $node->type .'|'. opensource_omniture_clean($node->title);
  }

  $vars = array(
    'variables' => array(
      's.pageName' => drupal_to_js($page_name),
      's.server' => "",
      's.channel' => "opensource",
      's.pageType' => "",
      's.prop1' => "",
      /* E-commerce Variables */
      's.campaign' => "",
      's.eVar1' => "",
      's.eVar2' => "",
      's.eVar3' => "",
      's.events' => "",
      's.products' => "",
      's.state' => "",
      's.zip' => "",
      's.purchaseID' => "",
    ),
  );

  return $vars;
}

/**
 * Clean a variable for javaScript
 * @param $var
 *   Variable to be cleaned for JavaScript.
 *
 * @return string
 *   Variable to pass to JavaScript.
 */
function opensource_omniture_clean($var) {
  $var = str_replace(' ', '-', $var);
  $var = str_replace('|', '', $var);
  return $var;
}