<?php

/**
 * @file
 * Add custom variables to opensource.com for Omniture SiteCatalyst.
 */

/**
 * Implementation of hook_omniture_variables().
 */
function opensource_omniture_omniture_variables($main) {
  global $user;

  // Every page starts with the site name.
  $page_name = 'opensource';

  // The user is on the homepage.
  if (drupal_is_front_page()) {
    $page_name .= '|home';
  }

  // The user is viewing a user page.
  elseif (arg(0) == 'user') {
    // Viewing a user page
    if (is_numeric(arg(1))) {
      $account = user_load(array('uid' => arg(1)));
      $page_name .= '|users|'. opensource_omniture_clean($account->name);
    }
    // On the registration form.
    elseif (arg(1) == 'register') {
      $page_name .= '|user|register';
    }
    // On the login form.
    elseif (arg(1) == 'login' || ($user->uid == 0 && arg(1) == '')) {
      $page_name .= '|user|login';
    }
  }

  // The user is searching
  elseif (arg(0) == 'search') {
    if (arg(1) == 'apachesolr_search') {
      $page_name .= '|contentsearch';
      if (arg(2) != '') {
        $page_name .= '|'. opensource_omniture_clean(arg(2));
      }
    }
    elseif (arg(1) == 'user') {
      $page_name .= '|usersearch';
      if (arg(2) != '') {
        $page_name .= '|'. opensource_omniture_clean(arg(2));
      }
    }
  }
  // The user is viewing a node homepage.
  elseif (arg(0) == 'node' && is_numeric(arg(1)) && $node = node_load(arg(1))) {
    $group_node = og_get_group_context();
    if ($node->type == 'post') {
      $page_name .= '|'. strtolower(opensource_omniture_clean($group_node->title)) .'|article|'. opensource_omniture_clean($node->title);
    }
    elseif ($node->type == 'channel') {
      $page_name .= '|'. strtolower(opensource_omniture_clean($group_node->title)) .'|home';
    }
    elseif ($node->type == 'poll') {
      $page_name .= '|'. strtolower(opensource_omniture_clean($group_node->title)) .'|poll|'. opensource_omniture_clean($node->title);
    }
    elseif ($node->type == 'page' || $node->type == 'group_page') {
      $path = drupal_get_path_alias($_GET['q']);
      $path = explode('/', $path);
      $page_name .= '|page';
      foreach ($path as $part) {
        $page_name .= '|'. opensource_omniture_clean($part);
      }
    }
  }
  // If there are no other rules use the site url path.
  else {
    $path = drupal_get_path_alias($_GET['q']);
    $path = explode('/', $path);
    foreach ($path as $part) {
      $page_name .= '|'. opensource_omniture_clean($part);
    }
  }

  // @todo: Add in comment tracking and generic page tracking when details come to light.

  $vars = array(
    'variables' => array(
      's.pageName' => $page_name,
      's.server' => "",
      's.channel' => "opensource",
      's.pageType' => "",
      's.prop1' => "",
      /* E-commerce Variables */
      's.campaign' => "",
      's.eVar1' => "",
      's.eVar2' => "",
      's.eVar3' => "",
      's.events' => "",
      's.products' => "",
      's.state' => "",
      's.zip' => "",
      's.purchaseID' => "",
    ),
  );

  return $vars;
}

/**
 * Clean a variable for javaScript
 * @param $var
 *   Variable to be cleaned for JavaScript.
 *
 * @return string
 *   Variable to pass to JavaScript.
 */
function opensource_omniture_clean($var) {
  $var = str_replace(' ', '-', $var);
  $var = str_replace('|', '', $var);
  return $var;
}