<?php

include_once('opensource_related_content.features.inc');

function opensource_related_content_init() {
  $module_path = drupal_get_path('module', 'opensource_related_content');
  $full_path = $module_path .'/opensource_related_content.css';
  drupal_add_css($full_path);
}

function sitetheme_apachesolr_mlt_recommendation_block($docs, $delta) {
  $nid = filter_xss(arg(1));
  if(filter_xss(arg(0)) == 'node' && is_numeric($nid)) {
    $node = node_load($nid);
    if(in_array($node->type, array('post', 'video', 'podcast'))) {
      $links = array();
      foreach ($docs as $result) {
        $node = node_load($result->nid);
        $output .= "<div class='apachesolr-related-content-item'>";
        $image = empty($node->field_lead_image[0]['filepath']) ? $node->field_image[0]['imceimage_path'] : $node->field_lead_image[0]['filepath'];
        $domains = array('http://opensource.prod.acquia-sites.com', 'http://opensource.com/');
        $item = theme('imagecache', 'related_content_lead_thumbnail', str_replace($domains, '', $image), $node->title, $node->title);
        $item .= "<div class='apachesolr-related-content-item-title'>" . $node->title . "</div>";
        $output .= l($item, 'node/' . $result->nid, array('html' => TRUE));
        $output .= "</div>";
      }
    }
  } else {
    $output = theme_apachesolr_mlt_recommendation_block($docs, $delta);
  }
  return $output;
}
