<?php
/**
 * @file Implements custom modal when user's visit the site.
 *
 */

/**
 * Implementation of hook_init().
 */
function opensource_popup_init() {
  drupal_add_js(drupal_get_path('module', 'opensource_popup') .'/opensource_popup.js');
  drupal_add_css(drupal_get_path('module', 'opensource_popup') .'/opensource_popup.css');
}

/**
 * Implementation of hook_menu().
 */
function opensource_popup_menu() {
  $items['opensource_popup'] = array(
    'title' => 'Splash Page',
    'access callback' => TRUE,
    'page callback' => 'opensource_popup_page',
  );

  return $items;
}

/**
 *
 */
function opensource_popup_page() {
  $output = '<div class="popup">';
  $output .= '<img src="'. base_path() . drupal_get_path('module', 'opensource_popup') .'/opensource_popup.png" />';
  $output .= '<div class="popup-links" style="text-align: center;">';
  $output .= '<a class="popup-close" href="#" onclick="javascript:Lightbox.end(\'forceClose\');">Continue to opensource.com</a> | '. l('Celebrate with us', '1-year-anniversary');
  $output .= '</div>';
  $output .= '</div>';
  print $output;
}

/**
 * Implementation of hook_preprocess_page().
 */
function opensource_popup_preprocess_page(&$vars, $hook) {
  if (module_exists('lightbox2') && (module_exists('session_api')) && (arg(0) != 'opensource_popup')) {
    $sid = session_api_get_sid();
    $session_id = db_result(db_query("SELECT session_id FROM {session_api} WHERE sid = %d", $sid));
    $status = db_result(db_query("SELECT COUNT(*) FROM {opensource_popup} WHERE sid = '%s'", $session_id));
    if (!$status) {
      $vars['content'] = l('Popup Ad', 'opensource_popup/lightbox2', array('attributes' => array('class' => 'hidden', 'rel' => 'lightmodal[|width:930px;height:640px; scrolling: none;]', 'id' => 'popup-ad'))) . $vars['content'];
      opensource_popup_insert($session_id);
    }
  }
}

/**
 * Add the Session ID.
 */
function opensource_popup_insert($session_id) {
  db_query("INSERT INTO {opensource_popup} values ('%s', %d)", $session_id, 0);
}
