<?php
// $Id$

/**
 * @file
 * Main functions for IMCE Caption module.
 */

// Load the theme functions.
module_load_include('theme', 'imce_caption');


/**
 * Save the caption for the given file.
 *
 * @param $fid
 *   The file ID.
 * @param $filepath
 *   The file path.
 * @param $caption
 *   The caption to save.
 * @return
 *   NULL
 */
function imce_caption_save($fid, $filepath, $caption) {
  $data = array(
    'fid' => $fid,
    'filepath' => $filepath,
    'caption' => $caption,
  );
  drupal_write_record('imce_captions', $data);
}

/**
 * Retrieve the caption for the given file.
 *
 * @param $file
 *   An array containing either the file's 'fid' or 'filepath'.
 * @return
 *   A string containing the caption.
 */
function imce_caption_load($file) {
  // Load the caption based on the filepath.
  if (!empty($file['filepath'])) {
    $result = db_fetch_array(db_query("SELECT caption FROM {imce_captions} WHERE filepath = '%s'", $file['filepath']));
  }
  // Load the caption based on the fid.
  elseif (!empty($file['fid'])) {
    $result = db_fetch_array(db_query('SELECT caption FROM {imce_captions} WHERE fid = %d', $file['fid']));
  }
  return $result ? $result['caption'] : '';
}

/**
 * Delete the caption for the given file.
 *
 * @param $file
 *   An array containing either the file's 'fid' or 'filepath'.
 * @return
 *   NULL
 */
function imce_caption_delete($file) {
  // Delete the caption based on the filepath.
  if (!empty($file['filepath'])) {
    db_query("DELETE FROM {imce_captions} WHERE filepath = '%s'", $file['filepath']);
  }
  // Delete the caption based on the fid.
  elseif (!empty($file['fid'])) {
    db_query('DELETE FROM {imce_captions} WHERE fid = %d', $file['fid']);
  }
}

/**
 * Implements hook_form_alter().
 */
function imce_caption_form_imce_upload_form_alter(&$form, $form_state) {
  // Move the thumbnails lower.
  $form['fset_upload']['thumbnails']['#weight'] = 10;
  // Add a caption field below the file upload field.
  $form['fset_upload']['caption'] = array(
    '#type' => 'textfield',
    '#title' => t('Caption'),
  );
  // Add a submit handler.
  $form['fset_upload']['upload']['#submit'][] = 'imce_caption_upload_form_submit';
}

/**
 * Submit handler for IMCE upload form.
 */
function imce_caption_upload_form_submit(&$form, $form_state) {
  // Get the files added to IMCE.
  $imce = $form['#parameters'][2]['imce'];
  foreach ($imce['added'] as $file) {
    $filepath = file_directory_path() . ($imce['dir'] == '.' ? '' : '/'. $imce['dir']) .'/'. $file['name'];
    imce_caption_save($file['id'], $filepath, $form_state['values']['caption']);
  }
}

/**
 * Implements hook_form_alter().
 */
function imce_caption_form_imce_fileop_form_alter(&$form, $form_state) {
  // Add submit handler for delete button before any other handlers.
  $form['fset_delete']['delete']['#submit'] = array_merge(
    array('imce_caption_delete_form_submit'),
    $form['fset_delete']['delete']['#submit']
  );
}

/**
 * Submit handler for IMCE delete form.
 */
function imce_caption_delete_form_submit(&$form, $form_state) {
  // Retrieve the IMCE data.
  $imce = $form['#parameters'][2]['imce'];
  foreach ($form_state['values']['filenames'] as $filename) {
    $filepath = file_directory_path() . ($imce['dir'] == '.' ? '' : '/'. $imce['dir']) .'/'. $filename;
    // Delete the caption.
    imce_caption_delete(array('filepath' => $filepath));
  }
}

/**
 * Implements hook_theme().
 */
function imce_caption_theme() {
  return array(
    'imce_caption_imagecache' => array(
      'arguments' => array(
        'presetname' => NULL,
        'path' => NULL,
        'alt' => '',
        'title' => '',
        'attributes' => NULL,
        'getsize' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function imce_caption_theme_registry_alter(&$registry) {
  // Store the name of the original theme function.
  if ($registry['imagecache']['function'] != 'theme_imagecache') {
    variable_set('imce_caption_imagecache_function', $registry['imagecache']['function']);
  }
  else {
    variable_del('imce_caption_imagecache_function');
  }
  // Our theme function will just be a wrapper function.
  $registry['imagecache']['function'] = $registry['imce_caption_imagecache']['function'];
}
