<?php
// $Id: unique_avatar.module,v 1.2.4.1 2008/12/15 16:04:42 jscheel Exp $

/**
 * @file unique_avatar.module
 *
 * Full module implementation, creates unique user picture filenames
 */

function unique_avatar_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_profile_form' && variable_get('user_pictures', 0) && !$register) {
    $key = array_search('user_validate_picture', $form['#validate']);
    if ($key !== FALSE) {
      $form['#validate'][$key] = 'unique_avatar_validate_picture';
    }
  }
}

function unique_avatar_validate_picture(&$form, &$form_state) {
  // If required, validate the uploaded picture.
  $validators = array(
    'file_validate_is_image' => array(),
    'file_validate_image_resolution' => array(variable_get('user_picture_dimensions', '85x85')),
    'file_validate_size' => array(variable_get('user_picture_file_size', '30') * 1024),
  );
  if ($file = file_save_upload('picture_upload', $validators)) {
    // The image was saved using file_save_upload() and was added to the
    // files table as a temporary file. We'll make a copy and let the garbage
    // collector delete the original upload.
    $info = image_get_info($file->filepath);
    $destination = variable_get('user_picture_path', 'pictures') .'/picture-'. $form['#uid'] . '-' . md5(time()) . '.' . $info['extension'];
    if (file_copy($file, $destination, FILE_EXISTS_REPLACE)) {
      $form_state['values']['picture'] = $file->filepath;
      // Remove the old picture.
      if (isset($form_state['values']['_account']->picture)) {
        if (module_exists('imagecache')) {
          imagecache_image_flush($form_state['values']['_account']->picture);
        }
        if (file_exists($form_state['values']['_account']->picture)) {
          file_delete($form_state['values']['_account']->picture);
        }
      }
    }
    else {
      form_set_error('picture_upload', t("Failed to upload the picture image; the %directory directory doesn't exist or is not writable.", array('%directory' => variable_get('user_picture_path', 'pictures'))));
    }
  }
}