<?php
/**
 * @file
 * Code for the OS core functionality.
 */
/**
 * Implements hook_install().
 * Here we will create two bean objects of generic_block bean type.
 *
 **/
function os_core_install() {

  $bean = bean_create(array('type' => 'generic_block'));
  $bean->label = 'Copyright Block';
  $bean->title = '<none>';
  $bean->delta = 'copyrigt-block';
  $bean->field_body['und'][0] = array(
    'value' => '<p>For more discussion on open source and the role of the CIO in the enterprise, join us at <a href="http://enterprisersproject.com">The EnterprisersProject.com</a>

      The opinions expressed on this website are those of each author, not of the author\'s employer or of Red Hat.

      opensource.com aspires to publish all content under a <a href="http://creativecommons.org/licenses/">Creative Commons license</a> but may not be able to do so in all cases. You are responsible for ensuring that you have the necessary permission to reuse any work on this site. Red Hat and the Shadowman logo are trademarks of Red Hat, Inc., registered in the United States and other countries.</p>',
    'format' => 'panopoly_wysiwyg_text' );
  $bean->save();



  $bean = bean_create(array('type' => 'generic_block'));
  $bean->label = 'Find us on Social Media';
  $bean->title = '<none>';
  $bean->delta = 'social-media';
  $bean->field_body['und'][0] = array(
    'value' => '<p><span class="find-us-text">Find us:</span> <a class="footer-identica" title="identi.ca" href="http://identi.ca/opensourceway">identi.ca</a> <a class="footer-youtube" title="Youtube" href="http://www.youtube.com/opensourceway">Youtube</a> <a class="footer-flickr" title="Flickr" href="http://www.flickr.com/photos/opensourceway">Flickr</a> <a class="footer-gplus" title="Google Plus" href="https://plus.google.com/108750398488318674353">Google Plus</a> <a class="footer-facebook" title="Facebook" href="http://www.facebook.com/pages/opensourcecom/162962298056">Facebook</a> <a class="footer-twitter" title="Twitter" href="https://twitter.com/OpenSourceWay">Twitter</a></p>',
    'format' => 'panopoly_wysiwyg_text' );
  $bean->save();

  block_flush_caches();
  db_update('block')
    ->fields(array(
      'status' => 1,
      'weight' => -10,
      'region' => 'navigation_top',
      'title' => '<none>',
    ))
    ->condition('module', 'menu')
    ->condition('delta', 'menu-about-menu')
    ->condition('theme', 'opensource')
    ->execute();

  db_update('block')
    ->fields(array(
      'status' => 1,
      'weight' => -12,
      'region' => 'footer',
    ))
    ->condition('module', 'bean')
    ->condition('delta', 'copyrigt-block')
    ->condition('theme', 'opensource')
    ->execute();

  db_update('block')
    ->fields(array(
      'status' => 1,
      'weight' => 0,
      'region' => 'footer',
      'title' => '<none>',
    ))
    ->condition('module', 'menu')
    ->condition('delta', 'menu-footer')
    ->condition('theme', 'opensource')
    ->execute();

  db_insert('block')
    ->fields(array(
      'module' => 'bean',
      'delta' => 'social-media',
      'theme' => 'opensource',
      'status' => 1,
      'weight' => 11,
      'region' => 'footer',
      'pages' => '',
      'cache' => 1,
    ))
    ->execute();
  db_update('menu_links')
    ->fields(array(
      'weight' => 50,
    ))
    ->condition('module', 'menu')
    ->condition('link_title', 'Feed')
    ->execute();

  variable_set('user_register', 2);
  $item = array(
    'link_title' => 'Sign Up',
    'link_path' => 'user/register',
    'menu_name' => 'user-menu',
    'weight' => 20,
  );
  $item['options']['attributes']['title'] = 'Sign Up';
  menu_link_save($item);

  //Creating the terms of vocabulary programatically
  //
  os_core_generate_taxonomy_terms();

}

/**
 * Implements hook_block_info()
 */
function os_core_block_info() {
  $blocks = array();
  $blocks['opensource-social-links'] = array(
    'info' => 'opensource: Social Links and subscription',
  );
  return $blocks;
}

/**
 *  Implements hook_block_view()
 */
function os_core_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'opensource-social-links':
      $block = array(
        'subject' => '<none>',
        'content' => os_core_display_social_block(),
       );
    break;
  }
  return $block;
}

function os_core_display_social_block() {
  $links = array();
  $links['twitter'] = array(
    'href' => 'http://twitter.com/opensourceway',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/twitter.jpg')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
  $links['facebook'] = array(
    'href' => 'http://facebook.com/pages/opensourcecom/162962298056',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/facebook.jpg')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
  $links['gplus'] = array(
    'href' => 'https://plus.google.com/108750398488318674353',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/gplus.png')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
  $links['flickr'] = array(
    'href' => 'http://www.flickr.com/photos/opensourceway',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/flickr_24x24.jpg')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
   $links['youtube'] = array(
    'href' => 'http://www.youtube.com/opensourceway',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/youtube.jpg')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
   $links['pinterest'] = array(
    'href' => 'http://pinterest.com/opensourceway/',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/pinterest.png')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
    $links['linkedin'] = array(
    'href' => 'http://www.linkedin.com/groups/Open-Source-Professionals-Advocates-2769297?gid=2769297',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/in.jpg')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
  $links['rss'] = array(
    'href' => 'http://opensource.com/feed',
    'title' => theme('image', array('path' => 'sites/all/themes/opensource/images/footer-social/osdc_rss_24x24.png')),
    'attributes' => array('target' => '_blank'),
    'html' => TRUE,
  );
  $output = theme('links', array(
      'links' => $links,
      'attributes' => array('class' => array('social-links', 'inline')),
    )
  );

  /*$output .= theme('image', array(
      'path' => 'sites/all/themes/sitetheme/images/email-signup.png',
      'alt' => 'Sign up for our newsletter',
      'title' => 'Sign up for our newsletter',
      'attributes' => array('class' => 'newsletter'),
    )
  );*/
  $output .= '<div class="signup-email-title">' . t('Sign-up for weekly email') . '</div>';
  $eloqua_form = drupal_get_form('os_core_eloqua_form');
  $output .= render($eloqua_form);
  return $output;
}

/**
 * Implements hook_init().
 */
function os_core_init(){
  if(array_key_exists('success', $_REQUEST)) {
    drupal_set_message('Thank you. You have been subscribed to our weekly email.');
  }
}

function os_core_eloqua_form($form, &$form_submit){
  // Build the Redirect
  $redirect = url('thank-you-subscription', array('absolute' => TRUE));

  $form['C_EmailAddress'] = array(
    '#type' => 'textfield',
    '#default_value' => '',
    '#size' => 24,
    '#maxlength' => 96,
  );
  $form['elqFormName'] = array(
    '#type' => 'hidden',
    '#value' => 'opensourcedotcom-subscription',
  );

  $form['elqSiteID'] = array(
    '#type' => 'hidden',
    '#value' => 1795,
  );

  $form['sendToURL'] = array(
    '#type' => 'hidden',
    '#value' => check_url($redirect),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Sign Up'),
  );
  $form['#action'] = 'https://secure.eloqua.com/e/f2.aspx';
  $form['#id'] = 'opensourcedotcom-subscription';

  return $form;
}

function os_core_eloqua_form_validate($form, &$form_state) {
  if ($form_state['values']['c_EmailAddress'] == '') {
    form_set_error('name', t('You must enter a valid email address.'));
  }
}

function os_core_generate_taxonomy_terms() {
  $vocabularies = taxonomy_get_vocabularies('article');
  foreach ($vocabularies as $vocab) {
    if($vocab->machine_name == 'channel'){
      $channelvid = $vocab->vid;
    }
    elseif($vocab->machine_name == 'article_type'){
      $article_type_vid = $vocab->vid;
    }
  }

  //Business Taxonomy
  $fid = os_core_file_upload('business');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Business';
  $term->description = 'Business';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="http://opensource.com/business/14/1/drupal-history?sc_cid=70160000000c9pFAAQ">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  //Education Taxonomy term
  $fid = os_core_file_upload('education');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Education';
  $term->description = 'Education';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="https://opensource.com/education/14/1/upgrade-to-open-source-in-schools?sc_cid=70160000000c9pPAAQ">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  //Government Term generation
  $fid = os_core_file_upload('government');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Government';
  $term->description = 'Government';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="https://opensource.com/government/13/12/government-year-in-review-2013?sc_cid=70160000000c9pZAAQ">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  // Health Term generation
  $fid = os_core_file_upload('health');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Health';
  $term->description = 'Health';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="https://opensource.com/health/13/12/health-science-year-in-review-2013?sc_cid=70160000000c9poAAA">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  // Law term generation
  $fid = os_core_file_upload('Law');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Law';
  $term->description = 'Law';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="https://opensource.com/law/13/12/year-in-review-law-2013?sc_cid=70160000000c9pyAAA">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  // Life term generation
  $fid = os_core_file_upload('life');
  $term = new stdClass();
  $term->vid = $channelvid;
  $term->name = 'Life';
  $term->description = 'Life';
  $term->field_readers_favourite['und'][0]['value'] = '<p><a href="https://opensource.com/life/13/12/top-open-source-projects-2013?sc_cid=70160000000c9ptAAA">[[{"fid":"'.$fid.'","view_mode":"default","fields":{"format":"default","field_file_image_alt_text[und][0][value]":"Reader\'s Favourite","field_file_image_title_text[und][0][value]":"","field_file_image_caption[und][0][value]":"","field_file_image_caption[und][0][format]":"panopoly_wysiwyg_text"},"type":"media","attributes":{"height":"135","width":"325","class":"media-element file-default"},"link_text":null}]]</a></p>';
  $term->field_readers_favourite['und'][0]['format'] = 'panopoly_wysiwyg_text';
  taxonomy_term_save($term);

  //Generating the terms of article_type vocabulary.
  $term = new stdClass();
  $term->vid = $article_type_vid;
  $term->name = 'article';
  $term->description = 'Article';
  taxonomy_term_save($term);
}

function os_core_file_upload($filename){
  $file = drupal_get_path('module', 'os_core') .'/images/'.$filename.'.png';
  if (file_exists($file)){
    $dfile = (object) array(
      'uri' => $file,
      'filemime' => file_get_mimetype($file),
      'status' => 1,
    );
    $drupalfile = file_copy($dfile, 'public://');
    $fid = $drupalfile->fid;
  }
  return $fid;
}
