<?php
/**
 * @file
 * Code for the OS block functionality.
 */

/**
 * Save or update a bean.
 */
function os_block_bean_save($bean_data) {
  $bean = bean_delta_load($bean_data['delta']);
  if (!$bean) {
    $bean = bean_create(array(
      'type' => !empty($bean_data['type']) ? $bean_data['type'] : 'generic_block',
      'delta' => $bean_data['delta'],
    ));
  }

  $bean->title = $bean_data['title'];
  $bean->label = $bean_data['label'];
  $bean->field_body = array(
    LANGUAGE_NONE => array(
      0 => array(
        'value' => $bean_data['body'],
        'format' => !empty($bean_data['format']) ? $bean_data['format'] : 'panopoly_wysiwyg_text',
      ),
    ),
  );

  $bean->save();
}

/**
 * Place block by either inserting or updating.
 */
function os_block_place_block($module, $delta, $theme, $fields) {
  $fields += array('pages' => '');
  db_merge('block')
    ->key(array('theme' => $theme, 'delta' => $delta, 'module' => $module))
    ->fields($fields)
    ->execute();
}
