<?php

/**
 * @file
 * Special urls for channels
 */

/**
 * Implementation of hook_menu().
 */
function channel_urls_menu() {
  $items['channel/%node/moderation-articles'] = array(
    'title' => 'Articles Awaiting Review',
    'page callback' => 'channel_urls_moderation_articles',
    'page arguments' => array('channel_awaiting_moderation', 'default', 1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'channel_urls_admin_access',
    'access arguments' => array(1),
  );

  return $items;
}

/**
 * Access callback. Determine if a user can see the articles awaiting review.
 */
function channel_urls_admin_access($gid) {
  $view = views_get_view('channel_awaiting_moderation');
  return og_is_group_admin($gid) && !$view->disabled;
}

/**
 * Menu callback. Display the articles awaiting review for a channel.
 */
function channel_urls_moderation_articles($view_name, $display, $node) {
  $arg = $node->nid;
  return views_page($view_name, $display, $arg);
}

/**
 * Implementation of hook_og_links_alter().
 */
function channel_urls_og_links_alter(&$links, $node) {
  $links['articles_awaiting_moderation'] = l('Articles awaiting review', 'channel/'. $node->nid .'/moderation-articles');
}