<?php
// $Id: omniture.module,v 1.6.4.3 2009/09/23 23:18:18 greggles Exp $
/*
 * @file
 * Drupal Module: Omniture SiteCatalyst Stats
 * Adds the required Javascript to the bottom of all your Drupal pages
 * to allow tracking by the Omniture SiteCatalyst statistics package.
 * Based on the Google Analytics package by Mike Carter
 *
 * @author: Greg Knaddison
 * @co-maintainer: Matthew Tucker
 *
 */

function omniture_help($path, $arg) {
  switch ($path) {
    case 'admin/help#omniture':
      return t("Settings for Omniture's SiteCatalyst package");
  }
}

function omniture_perm() {
  return array('administer SiteCatalyst configuration');
}

/**
 * Implementation of hook_menu
 */
function omniture_menu() {
  $items = array();

  $items['admin/settings/omniture'] = array(
    'title' => 'SiteCatalyst',
    'description' => 'Configure the settings used to integrate Omniture\'s SiteCatalyst.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('omniture_admin_settings'),
    'access arguments' => array('administer SiteCatalyst configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_footer()  to insert Javascript at the end of the page
 */
function omniture_footer($main = 0) {

  global $user;

  // Check if we should track the currently active user's role
  $track = 0;
  foreach ($user->roles as $role) {
    $role = str_replace(' ', '_', $role);
    $track += variable_get("omniture_track_{$role}", FALSE);
  }

  // Don't track page views in the admin sections, or for certain roles
  if (arg(0) != 'admin' && $track > 0) {

    // Add any custom code snippets if specified
    $codesnippet = variable_get('omniture_codesnippet', '');

    // Taxonomy specific stuff - only for nodes
    if (module_exists('taxonomy') && $node = menu_get_object()) {
      $tax = $node->taxonomy;

      $vocabularies = taxonomy_get_vocabularies();
      foreach ($vocabularies as $vid => $vocab) {
        if ($vocab->tags == 0) {
          if ($variable_name = variable_get("omniture_vocabvidvar_{$vocab->vid}", FALSE)) {
            $terms_for_omniture = "";
            foreach ($node->taxonomy as $tid => $taxonomy) {
              if ($taxonomy->vid == $vid) {
                if (strlen($terms_for_omniture) > 0) {
                  $terms_for_omniture .= ','. $taxonomy->name;
                }
                else {
                  $terms_for_omniture .= $taxonomy->name;
                }
              }
            }
            if (isset($terms_for_omniture)) {
              $omniture_vocab_vars[$variable_name] = $terms_for_omniture;
            }
          }
        }
      }
    }

    // Format and combine variables in the "right" order
    // Right order is the code file (least likely to be maintained)
    // Then admin settings with codesnippet first and finally taxonomy->vars
    $extra_variables_formatted = $codesnippet;

    if (isset($omniture_vocab_vars)) {
      foreach ($omniture_vocab_vars as $variable => $value) {
        $extra_variables_formatted .= "\n". $variable .'='. $value .';';
      }
    }

    $header = "<!-- SiteCatalyst code version: ";
    $header .=  check_plain(variable_get("omniture_version", 'H.13.'));
    $header .= " Copyright 1997-2009 Omniture, Inc. More info available at http://www.omniture.com -->\n";
    $header .= "<script type=\"text/javascript\" language=\"JavaScript\" src=\"";
    $header .=  check_plain(variable_get("omniture_js_file_location", 'http://www.example.com/js/s_code_remote_h.js'));
    $header .= "\"></script>\n";
    $header .= "<script type=\"text/javascript\" language=\"JavaScript\"><!--\n";

    $footer = '/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/'."\n";
    $footer .= 'var s_code=s.t();if(s_code)document.write(s_code)//--></script>'."\n";
    $footer .= '<script language="JavaScript" type="text/javascript"><!--'."\n";
    $footer .= "if(navigator.appVersion.indexOf('MSIE')>=0)document.write(unescape('%3C')+'\!-'+'-')"."\n";
    $footer .= '//--></script><noscript><a href="http://www.omniture.com" title="Web Analytics"><img src="';
    $footer .= check_plain(variable_get("omniture_image_file_location", 'http://examplecom.112.2O7.net/b/ss/examplecom/1/H.13--NS/0')) .'"'."\n";
    $footer .= 'height="1" width="1" border="0" alt="" /></a></noscript><!--/DO NOT REMOVE/-->'."\n";
    $footer .= '<!-- End SiteCatalyst code version: ';
    $footer .=  check_plain(variable_get("omniture_version", 'H.13.'));
    $footer .= ' -->'."\n";

    // Get variables other modules have set.
    $extra_variables = omniture_get_variables();

    if ($omniture_hooked_vars = module_invoke_all('omniture_variables', $main)) {
      if (isset($omniture_hooked_vars['header'])) {
        $header = $omniture_hooked_vars['header'];
      }
      if (isset($omniture_hooked_vars['variables'])) {
        // We need to merge some variables here.
        foreach ($omniture_hooked_vars['variables'] as $k => $v) {
          if (is_array($v)) {
            $v = $v[count($v)-1];
          }
          if (isset($extra_variables[$k])) {
            $v = $extra_variables[$k];
          }
          $extra_variables_formatted .= "$k=$v;\n";
        }
      }
      if (isset($omniture_hooked_vars['footer'])) {
        $footer = $omniture_hooked_vars['footer'];
      }
    }

    $script  = $header;
    $script .= $extra_variables_formatted;
    $script .= $footer;

    return $script;
  }
}

/**
 * Implementation of hook_admin_settings() for configuring the module
 */
function omniture_admin_settings() {
  $form['general'] = array(
        '#type' => 'fieldset',
        '#title' => t('General Settings'),
        '#collapsible' => TRUE,
        '#description' => t('General settings')
  );

  $form['general']['omniture_js_file_location'] = array(
      '#type' => 'textfield',
      '#title' => t("Complete path to SiteCatalyst Javascript file"),
      '#default_value' => check_plain(variable_get("omniture_js_file_location", 'http://www.example.com/js/s_code_remote_h.js')),
  );

  $form['general']['omniture_image_file_location'] = array(
      '#type' => 'textfield',
      '#title' => t("Complete path to SiteCatalyst Image file"),
      '#default_value' => check_plain(variable_get("omniture_image_file_location", 'http://examplecom.112.2O7.net/b/ss/examplecom/1/H.13--NS/0')),
  );

  $form['general']['omniture_version'] = array(
      '#type' => 'textfield',
      '#title' => t("SiteCatalyst version (used by omniture for debugging)"),
      '#default_value' => check_plain(variable_get("omniture_version", 'H.13')),
  );

  // Render the role overview.
  $result = db_query('SELECT * FROM {role} ORDER BY name');

  $form['roles'] = array(
        '#type' => 'fieldset',
        '#title' => t('User Role Tracking'),
        '#collapsible' => TRUE,
        '#description' => t('Define what user roles should be tracked by SiteCatalyst.')
  );

  while ($role = db_fetch_object($result)) {
     // can't use empty spaces in varname
    $role_varname = $string = str_replace(' ', '_', $role->name);
    $form['roles']["omniture_track_{$role_varname}"] = array(
      '#type' => 'checkbox',
      '#title' => t($role->name),
      '#default_value' => variable_get("omniture_track_{$role_varname}", FALSE),
    );
  }

  $form['vocabs'] = array(
        '#type' => 'fieldset',
        '#title' => t('Vocabulary Variables'),
        '#collapsible' => TRUE,
        '#description' => t('Define which vocabularies should should be tracked by which SiteCatalyst variables.  Only applies to the full node view (e.g. node/1 or the aliased version of a node). Leave blank to disable for a vocabulary.  Multiple terms from a "Multiple select" vocabulary will be placed into a comma separated list.  Not available for "Free tagging" vocabularies.')
  );

  // Allow setting a vocabulary into a variable
  if (module_exists('taxonomy')) {
    $vocabularies = taxonomy_get_vocabularies();
    foreach ($vocabularies as $vid => $vocab) {
      if ($vocab->tags == 0) {
        $form['vocabs']["omniture_vocabvidvar_{$vocab->vid}"] = array(
          '#type' => 'textfield',
          '#title' => t('Variable for %vocab', array('%vocab' => $vocab->name)),
          '#default_value' => variable_get("omniture_vocabvidvar_{$vocab->vid}", FALSE),
        );
      }
    }
  }

  $form['advanced'] = array(
        '#type' => 'fieldset',
        '#title' => t('Advanced'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#description' => t('You can add custom SiteCatalyst code here.')
  );

  $form['advanced']['omniture_codesnippet'] = array(
      '#type' => 'textarea',
      '#title' => t('JavaScript Code'),
      '#default_value' => variable_get('omniture_codesnippet', ''),
      '#rows' => 15,
      '#description' => t('Paste <a href="@snippets">custom code snippets here</a>. These will be added to every page that SiteCatalyst appears on. For help with this feature see the <a href="@blog">cutroni.com blog</a>. <strong>Do not include the &lt;script&gt; tags</strong>, and always end your code with a semicolon (;).', array('@snippets' => 'http://drupal.org/node/39282', '@blog' => 'http://cutroni.com/blog/') )
  );

  return system_settings_form($form);
}

/**
 * Builds up a set of properties and values ot add to the JS of the page.
 *
 * @param string $name
 *  The property.
 * @param string $value
 *  The value for the property.
 */
function omniture_set_variable($name = NULL, $value = NULL) {
  static $variables;
  if (empty($name)) {
    return $variables;
  }
  else {
    $variables[$name] = $value;
  }
}

function omniture_get_variables() {
  return omniture_set_variable();
}

/**
 * Example output from the omniture.com site itself.
 * Some of the paths may not be applicable for your site but at least it provides an example.
 */

/*

<!-- SITECATALYST CODE -->
<script language="javascript" src="/js/s_code_remote_h.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
<!--
// Copyright 1997-2004 Omniture, Inc.

// PAGE SPECIFIC VIA ISOL G & H

var s_pageName='Omniture: Homepage';
var s_channel='Home';
var s_prop7='English';
s.pageName='Omniture: Homepage';
s.channel='Home';
s.prop6='English';

// END PAGE SPECIFIC VIA ISOL

// SiteCatalyst code version: G.7.
var s_server="www.omniture.com"
  var s_campaign=""
  var s_events=""
  var s_products=""
  var s_prop1="Non-Customer"
  var s_prop15=""
  var s_prop16=""
  var s_eVar3 = ""
  var s_eVar4 = ""
  var s_eVar5 = ""
  var s_eVar6 = ""
  var s_eVar7 = ""
  var s_eVar8 = ""
  var s_eVar9 = ""
  var s_eVar10 = ""
  var s_eVar11 = ""
  var s_eVar13 = ""
  var s_eVar14 = ""
  var s_eVar15 = ""
  // END G.7 CODE IMPLEMENTATION

  // H.1 CODE BEGIN
  s.server="www.omniture.com"
  s.campaign=""
  s.events=""
  s.products=""
  s.prop1="Non-Customer"
  s.prop3="Natural Search (All Other Engines)|"+s.pageName
  s.prop5="Untracked"
  s.prop14=""
  s.prop15=""
  s.prop16=""
  s.prop17=""
  s.prop18=""
  s.prop19=""
  s.prop20="Non-Customer"
  s.prop21=""
  s.prop22=""
  s.prop23=""
  s.prop24=""
  s.prop25=""
  s.prop26=""
  s.prop27=""
  s.prop28=""
  s.prop30=""
  s.prop32="67.41.129.163"
  s.prop33=""
  s.prop34=""
  s.prop35=""
  s.eVar7=""
  s.eVar8=""
  s.eVar9=""
  s.eVar10=""
  s.eVar11=""
  s.eVar13=""
  s.eVar28=""
  s.eVar33=""
  // H.1 CODE END

  var s_code=s.t();if(s_code)document.write(s_code)
         //-->
         </script>
         <script language="javascript" src="/js/s_code_remote_g.js" type="text/javascript"></script>
         <noscript>
         <img src="http://omniturecom.112.2O7.net/b/ss/omniturecom/1/H.7--NS/0" height="1" width="1" border="0" alt="" />
         </noscript>


         <!-- BANNER TRACKING IF ANY -->
         <script language="javascript" src="/js/functions.js"></script>
         <script language="javascript" src="/js/banner_track.js"></script>
         <!-- END SITECATALYST CODE -->

*/
