<?php
/**
 * @file
 * os_user_page.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function os_user_page_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'reg_with_pic_enabled';
  $strongarm->value = 1;
  $export['reg_with_pic_enabled'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'reg_with_pic_weight';
  $strongarm->value = '0';
  $export['reg_with_pic_weight'] = $strongarm;

  return $export;
}
