<?php

/**
 * Implementation of hook_form_alter
 */
function opensource_form_alter(&$form, &$form_state, $form_id) {
 // If we have a lead image, we know we should include an /imce upload link
 if($form['field_lead_image']) {
  $form['imce_link'] = array(
    '#type' => 'markup',
    '#weight' => -10,
    '#value' => l("Upload Images", "imce", array('attributes' => array('target' => '_blank'))),
  );
 }
}

/**
 * Implementation of hook_block
 */
function opensource_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case "list":
      $blocks = array();
      $blocks[1] = array(
        'info' => t('opensource: Social Links'),
        'status' => 1,
        'weight' => 10,
      );
      return $blocks;
    case "view":
      if($delta == 1){
        $block = array(
          'subject' => 'Stay Connected',
          'content' => opensource_display_social_block(),
        );
      }
      return $block;
  }
}

function opensource_display_social_block() {
  return "Here is some content";
}