<?php
/**
 * @file
 * This contains code to register and support core migration from OS6 -> 7.
 */

/**
 * Implements hook_flush_caches().
 */
function os_migrate_flush_caches() {
  os_migrate_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function os_migrate_register_migrations() {
  // These are our common arguments for all our migrations.
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_database' => array(
      'driver' => 'mysql',
      'database' => 'os6',
      'username' => 'hwdb',
      // Best practice: use a variable (defined by setting $conf in settings.php
      // or with drush vset) for the password rather than in the code.
      'password' => variable_get('os_migrate_password', 'hussainweb'),
      'host' => 'localhost',
    ),
    'source_version' => 6,
    'group_name' => 'opensource',
  );

  // Register User Picture migration.
  $args = $common_arguments + array(
    'description' => t('Migration of user pictures'),
    'machine_name' => 'OsUserPicture',
    'source_dir' => 'http://opensource.com/sites/default/files',
  );

  Migration::registerMigration('DrupalPicture6Migration', $args['machine_name'], $args);

  // Register User migration.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'OsUser',
    'dependencies' => array('OsUserPicture'),
  );

  Migration::registerMigration('OsMigrateUserMigration', $arguments['machine_name'], $arguments);

  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
  $node_arguments = array(
    array(
      'class_name' => 'ExampleImageMigration',
      'description' => t('Migration of image nodes from Drupal 6'),
      'machine_name' => 'Image',
      'source_type' => 'image',
      'destination_type' => 'image',
    ),
    array(
      'class_name' => 'ExampleArticleMigration',
      'description' => t('Migration of article nodes from Drupal 6'),
      'machine_name' => 'Article',
      'source_type' => 'my_article',
      'destination_type' => 'new_article',
      'dependencies' => array('Image', 'Countries', 'Topics'),
    ),
  );
  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D6->D7 uids.
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'User',
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    //Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  }

  // Menu migrations -- same requirements as users
  $menu_arguments = $common_arguments + array(
    'description' => t('Migration of menus from Drupal 6'),
    'machine_name' => 'Menu',
  );

  // We just use the migrate_d2d D6 migration class as-is.
  //Migration::registerMigration('DrupalMenu6Migration', $menu_arguments['machine_name'], $menu_arguments);

  // Menu links migrations -- basic requirements, plus must set up menu dependency
  $menu_links_arguments = $common_arguments + array(
    'description' => t('Migration of menu links from Drupal 6'),
    'machine_name' => 'MenuLinks',
    'menu_migration' => $menu_arguments['machine_name'],
  );
  //Migration::registerMigration('DrupalMenuLinks6Migration', $menu_links_arguments['machine_name'], $menu_links_arguments);
}

/**
 * Implements hook_migrate_api().
 */
function os_migrate_migrate_api() {
  $disable_hooks = array(
    'user_insert' => array(
      'os_badges',
    ),
  );

  $api = array(
    'api' => 2,
    'groups' => array(
      'opensource' => array(
        'title' => 'OpenSource.com D6->D7 migration',
        'disable_hooks' => $disable_hooks,
      ),
    ),
  );
  return $api;
}
