<?php
/**
 * @file
 * os_homepage.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function os_homepage_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "quicktabs" && $api == "quicktabs") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function os_homepage_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_image_default_styles().
 */
function os_homepage_image_default_styles() {
  $styles = array();

  // Exported image style: homepage-thumb.
  $styles['homepage-thumb'] = array(
    'name' => 'homepage-thumb',
    'effects' => array(
      1 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'image_scale_form',
        'summary theme' => 'image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 162,
          'height' => 90,
          'upscale' => 0,
        ),
        'weight' => 1,
      ),
    ),
    'label' => 'homepage-thumb',
  );

  return $styles;
}
